name: pr

on:
  pull_request: # Automatischer Trigger bei Pull Requests
  workflow_dispatch: # Manueller Trigger

jobs:
  lint:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
