name: pr

on:
  pull_request: # Automatischer Trigger bei Pull Requests
  workflow_dispatch: # Manueller Triggerpush: 
  push: # Trigger bei Änderungen am Branch
    branches:
      - master # Nur wenn in master gepusht wird


jobs:
  lint:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
