name: pr

on:
  pull_request: # Automatischer Trigger bei Pull Requests
  workflow_dispatch: # Manueller Triggerpush: 


jobs:
  lint:
    name: pr
    runs-on: ubuntu-latest
    steps:
      # Check out the pull request branch
      - name: Check out pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # Hole vollständige Branch-Historie (falls nötig)

      # Check out the master branch in a different directory
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
          path: master-branch # Klone in ein separates Verzeichnis

      # Read the root file from the master branch
      - name: Read root file from master branch
        run: |
          if [ -f master-branch/rootfile ]; then
            CONTENT=$(cat master-branch/rootfile)
            echo "File content: $CONTENT"
            if [ "$CONTENT" = "1" ]; then
              echo "File contains 1. Failing the workflow."
              exit 1
            elif [ "$CONTENT" = "0" ]; then
              echo "File contains 0. Workflow will succeed."
            else
              echo "File contains unexpected content: $CONTENT. Failing the workflow."
              exit 1
            fi
          else
            echo "File does not exist in the root directory. Failing the workflow."
            exit 1
          fi
