name: Re-trigger Existing PR Checks

on:
  push:
    branches:
      - master # Löst aus, wenn in den master-Branch gepusht wird

jobs:
  retrigger-checks:
    name: Re-trigger Existing Checks
    runs-on: ubuntu-latest
    steps:
      - name: Fetch open Pull Requests targeting master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Hole alle offenen Pull Requests mit `master` als Ziel
          PRS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master")
          
          # Iteriere über die PRs und hole die Checks
          for pr in $(echo "$PRS" | jq -r '.[].head.sha'); do
            echo "Fetching checks for PR with SHA: $pr"

            # Hole bestehende Checks für den Commit
            CHECKS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/commits/$pr/check-runs")

            # Iteriere über die vorhandenen Checks und trigger sie neu
            echo "$CHECKS" | jq -r '.check_runs[].id' | while read check_id; do
              echo "Re-triggering check run ID: $check_id"
              curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/${{ github.repository }}/check-runs/$check_id/rerequest"
            done
          done
