name: Re-trigger Existing PR Jobs

on:
  push:
    branches:
      - master # Auslösen bei Änderungen im master-Branch

jobs:
  retrigger-jobs:
    name: Re-trigger Existing Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Fetch open Pull Requests targeting master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Hole alle offenen Pull Requests mit `master` als Ziel
          PRS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master")

          # Iteriere über die PRs und hole die Workflow-Runs
          for pr_branch in $(echo "$PRS" | jq -r '.[].head.ref'); do
            echo "Fetching Workflow-Runs for PR branch: $pr_branch"

            # Hole die Workflow-Runs für den PR-Branch
            RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=$pr_branch&status=completed")

            # Iteriere über die Runs und hole die Job-IDs
            echo "$RUNS" | jq -r '.workflow_runs[].jobs_url' | while read jobs_url; do
              JOBS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$jobs_url")
              echo "$JOBS" | jq -r '.jobs[].id' | while read job_id; do
                echo "Re-triggering job ID: $job_id"
                curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github+json" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/jobs/$job_id/rerun"
              done
            done
          done
